# Generated by Django 5.1.4 on 2025-02-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='resolutionTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('P0', 'Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='resolutionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('P0', 'Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], max_length=2, null=True),
        ),
    ]
