# Generated by Django 5.1.4 on 2025-02-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='assigned_date',
            field=models.DateTimeField(default='2021-09-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='resolutionDate',
            field=models.DateField(null=True),
        ),
    ]
