# Generated by Django 5.1.4 on 2025-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
