# Generated by Django 5.1.4 on 2025-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0002_alter_incidentissue_root_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
