# Generated by Django 5.1.4 on 2025-06-09 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0002_incidentissue_resolutiontime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('P0', 'Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], default='P4', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='resolutionDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='resolutionTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'In Progress'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'In Progress'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
