# Generated by Django 5.1.4 on 2025-01-17 10:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0003_alter_incidentissue_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='reporter',
            field=models.CharField(max_length=255, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='root_cause',
            field=models.TextField(default='No root cause provided'),
        ),
    ]
