# Generated by Django 5.1.4 on 2025-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
