# Generated by Django 5.1.4 on 2025-01-18 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0009_attachment_issueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'inprogress'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
