# Generated by Django 5.1.4 on 2025-01-20 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0010_attachment_uploaded_at_alter_attachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='NonsapIncidentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('report_date', models.DateField()),
                ('report_time', models.TimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('root_cause', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
