# Generated by Django 5.1.4 on 2025-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0015_incidentissue_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='custom_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='custom_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='NonsapIncidentIssue',
        ),
    ]
