# Generated by Django 5.1.5 on 2025-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0015_incidentissue_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'inprogress'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='NonsapIncidentIssue',
        ),
    ]
