# Generated by Django 5.1.5 on 2025-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0016_issue_status_delete_nonsapincidentissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='issue_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
