# Generated by Django 5.1.4 on 2025-01-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0016_incidentissue_custom_id_issue_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incidentissue',
            table='nonsap_incidentissue',
        ),
    ]
