# Generated by Django 5.1.5 on 2025-01-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0017_incidentissue_issue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
