# Generated by Django 5.1.4 on 2025-01-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0018_comment_image_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_at',
            new_name='created_at',
        ),
    ]
