# Generated by Django 5.1.5 on 2025-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0018_remove_incidentissue_status_remove_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissue',
            name='issue_id',
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='custom_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'inprogress'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
