# Generated by Django 5.1.4 on 2025-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0019_rename_commented_at_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
