# Generated by Django 5.1.5 on 2025-01-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0019_remove_incidentissue_issue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='custom_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
