# Generated by Django 5.1.5 on 2025-02-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0020_issue_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissue',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='incidentissue',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='incidentissue',
            name='assigned_to',
        ),
    ]
