# Generated by Django 5.1.4 on 2025-01-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0020_alter_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='commented_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
