# Generated by Django 5.1.4 on 2025-01-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0021_rename_created_at_comment_commented_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissue',
            name='assigned_staff',
        ),
    ]
