# Generated by Django 5.1.5 on 2025-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0021_remove_incidentissue_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], default='P3', max_length=2),
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='resolution_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
