# Generated by Django 5.1.5 on 2025-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0022_incidentissue_priority_incidentissue_resolution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], max_length=2),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='resolution_time',
            field=models.DateTimeField(default=0),
        ),
    ]
