# Generated by Django 5.1.4 on 2025-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0022_remove_incidentissue_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], default='P1', max_length=10),
        ),
    ]
