# Generated by Django 5.1.5 on 2025-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0023_alter_incidentissue_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='resolution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
