# Generated by Django 5.1.4 on 2025-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0023_incidentissue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='company_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('active', 'Active'), ('inprogress', 'inprogress'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
