# Generated by Django 5.1.5 on 2025-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0024_alter_incidentissue_resolution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='resolution_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
