# Generated by Django 5.1.4 on 2025-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0025_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='resolutionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
