# Generated by Django 5.1.4 on 2025-02-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0025_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
