# Generated by Django 5.1.5 on 2025-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0025_alter_incidentissue_resolution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissue',
            name='resolution_time',
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
