# Generated by Django 5.1.5 on 2025-02-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0026_remove_incidentissue_resolution_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentissue',
            name='number_of_days',
        ),
    ]
