# Generated by Django 5.1.4 on 2025-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0028_issue_custom_days_issue_priority_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], max_length=2, null=True),
        ),
    ]
