# Generated by Django 5.1.4 on 2025-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0029_alter_incidentissue_assigned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='assigned_date',
            field=models.DateTimeField(default='2021-09-01 00:00:00'),
        ),
    ]
