# Generated by Django 5.1.4 on 2025-02-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0030_alter_incidentissue_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentissue',
            name='resolutionDate',
            field=models.DateField(null=True),
        ),
    ]
