# Generated by Django 5.1.4 on 2025-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0031_alter_incidentissue_resolutiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
