# Generated by Django 5.1.4 on 2025-06-05 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0031_alter_incidentissue_resolutiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
