# Generated by Django 5.1.4 on 2025-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0032_incidentissue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
