# Generated by Django 5.1.4 on 2025-06-05 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0033_incidentissue_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
