# Generated by Django 5.1.4 on 2025-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0033_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='resolutionTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('P0', 'Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], max_length=2, null=True),
        ),
    ]
