# Generated by Django 5.1.4 on 2025-02-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0034_incidentissue_resolutiontime_alter_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentissue',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='priority',
            field=models.CharField(choices=[('P0', 'Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low'), ('P4', 'P4 - Custom')], default='active', max_length=10),
        ),
    ]
