# Generated by Django 5.1.4 on 2025-06-05 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsap', '0034_issue_status_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
